####################################################

# The input data:
NonRandom <- c(126, 326, 452)   #These are the results of the testing of the risk-based sample
ORs <- c(4.643392, 0.2907135)   #These are the parameters of the OR estimated using the model 'RiskBased settings 2.R'

#Structures:

#NonRandom
#Positives    Negatives   Tested

#ORs
#MeanOR    VarOR

####################################################

## The data:
NonRandom
ORs


## Load the runjags package and define the model:
library("runjags")


modelUseOR2 <- '
model{

	#ESTIMATION OF pi IN NON-RANDOM GROUP
	NonRandom[1] ~ dbin(apNR, NonRandom[3])   # Positives
	apNR <- pNR*Se+(1-pNR)*(1-Sp)   #Likelihood for the positives

	#PRIORS
	pNR~dbeta(1,2)       #Prior for the distribution of prevalence in Non-Random group

	#ESTIMATION OF  pi IN THE MISSING RANDOM GROUP FROM THE OR BETWEEN NON-RANDOM AND RANDOM
	taur <- 1/ORs[2]
	oddsr ~ dnorm(ORs[1],taur)T(0,)
	pR <- pNR/(pNR+oddsr-pNR*oddsr)

	#The other PRIORS
	Se ~ dbeta(57.35,12.589)              #Prior for Sensitivity
	Sp ~ dbeta(1000,1)              #Prior for Specificity


	#data# NonRandom, ORs
	#monitor# pR, pNR, Se, Sp, oddsr
	#inits# pNR, Se, Sp, oddsr

	}
'


# The initial values we need:
pNR <- list(chain1=0.1, chain2=0.4)
Se <- list(chain1=0.5, chain2=0.95)
Sp <- list(chain1=0.95, chain2=0.5)
oddsr <- list(chain1=0.1, chain2=100)


# Run the model:
resultsUseOR2 <- run.jags(modelUseOR2, n.chains=2, burnin = 4000, sample = 10000, thin=4)

# Check convergence:
plot(resultsUseOR2)

# Results:
resultsUseOR2

# Save results in table form:
write.csv(summary(resultsUseOR2), file='resultsUseOR2.csv')

## Extract MCMC chains:
library('coda')

chains <- as.mcmc(resultsUseOR2)
write.csv(chains,file='ChainsUseOr2.csv')

###############################
# Maybe give some more comments as to what is going on below here?

m<-as.numeric(NA)
v<-as.numeric(NA)
alpha<-as.numeric(NA)
beta<-as.numeric(NA)

#Now we calculate the mean and varians of the values generated by the model and stored in the chains
#m[1] and v[1] are the mean and variance for the variable pR
#m[2] and v[2] are for pNR
#m[3] and v[3] are for Se
#m[4] and v[4] are for Sp

#From these means and variances, we calculate the paameters Alpha and Beta of the corresponding posterior beta distributions

#m[5] and v[5] refer to the generated values of OR, which follow a normal distribution, not a beta dist

for(i in 1:4){
  
m[i]<-mean(chains[,i])
v[i]<-var(chains[,i])
alpha[i]<-((m[i]^2-m[i]^3-m[i]*v[i])/v[i])
beta[i]<-((m[i]-2*m[i]^2+m[i]^3-v[i]+m[i]*v[i])/v[i])

}
m[5]<-mean(chains[,5])
v[5]<-var(chains[,5])

#The following graphs compare the generated posterior distributions to the distributions described by the Alpha and Beta parameters calculated above

hist(chains[,1], freq = FALSE, xlim=c(0,1), col = "grey", main='pR')
curve(dbeta(x,alpha[1],beta[1]),col='blue', add=TRUE)

hist(chains[,2], freq = FALSE, xlim=c(0,1), col = "grey", main='pNR')
curve(dbeta(x,alpha[2],beta[2]),col='blue', add=TRUE)

hist(chains[,3], freq = FALSE, xlim=c(0,1), col = "grey", main='Se')
curve(dbeta(x,alpha[3],beta[3]),col='blue', add=TRUE)

hist(chains[,4], freq = FALSE, xlim=c(0,1), col = "grey", main='Sp')
curve(dbeta(x,alpha[4],beta[4]),col='blue', add=TRUE)

standev<-v[5]^0.5
hist(chains[,5], freq = FALSE, xlim=c(0,100), col = "grey", main='Odds ratio')
curve(dnorm(x,m[5],standev, log = FALSE),col='blue', add=TRUE)



#The following graphs compare Priors vs. Posteriors for sensitivity and specificity

hist(chains[,3], freq = FALSE, xlim=c(0,1), col = "grey", main='Prior vs Post Se')
curve(dbeta(x,57.35,12.589),col='blue', add=TRUE)

hist(chains[,4], freq = FALSE, xlim=c(0,1), col = "grey", main='Prior vs Post Sp')
curve(dbeta(x,1000,1),col='blue', add=TRUE)

